### ISSUE TITLE
Finalize the graphical style that will be used

### ISSUE THREAD

**Issue by AlmostPete** [ss31/ss31#10]
We need to finalize the graphical style to be used. Options:

* Could just do true 3D with isometric view
* Could do 3D->2D like SS14 and standalone
* Pure 2D - shying away from this as it would end up like the Byond version and we want an improvement

**Comment by Starrider814** [comment]
We will be using 64x64, 2d tiles and all objects&&items will be sprited to that scale. Characters and clothing will be rendered using a 3d>2d renderer that outputs characters at 64 pixels tall. The characters will be rendered in 3 layers, one for each arm and one for the rest of the body. Carried items will be pinned to whichever hand layer is carrying them so we get items to pass behind the body in a realistic fashion.

Whenever we start work on the renderer, let me know so I can get feedback about what you need from the models, and what I need it to do.

**Comment by cybergeek94** [comment]
For the 3d-2d rendering plugin in Blender I talked about, it would basically be automating [this process](http://youtu.be/Z3yOCJRaUxc).

**Comment by Starrider814** [comment]
It's finalized, for details check here or ask me when I'm around.

https://docs.google.com/document/d/1jxn4PCqCSDj9e6Pan6jq3gzjyffOTo91HPTYPg2qz18/edit?usp=sharing
