### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by johnku1** [ss31/ss31#13]
We should probably get a build system in place, so that people can try out dev-builds ( even if the code is kinda non-existent at the moment). I suggest Travis-CI or another free continuous integration system.

**Comment by AlmostPete** [comment]
What build system does SS14 use currently? Also, if we take a look at Travis CI, @cybergeek94 said that he has experience with Travis CI. If we decide to go with that, he can help us.

**Comment by cybergeek94** [comment]
I've gotten repos for Rust building on TravisCI. It's not overly complicated.

**Comment by AlmostPete** [comment]
I was just reading up on TravisCI's .NET language support, and it says that C# support is still in beta. Do we still want to use Travis CI then?

**Comment by AlmostPete** [comment]
Hey cyber I'm assigning this to you because of your CI experience. If you think that we could use Travis as a build system, you should go ahead and set that up, if you could. If not, could you look for another solution and implement it? Thanks.

**Comment by cybergeek94** [comment]
Looks like C# support is pretty solid. Do we have a test suite to run yet? Or just try to build the solutions.

**Comment by AlmostPete** [comment]
No test suite yet. I think we need to just try to build the solutions for now. Also a little badge in the README with the build status would be nice.

**Comment by cybergeek94** [comment]
I've started a branch for experimenting with integration. Am I free to push it to the repo?

**Comment by AlmostPete** [comment]
Yeah.

**Comment by cybergeek94** [comment]
Having some trouble getting the build going, I think because TravisCI uses Linux workers but the solution assumes Win32. I'm building my Linux VM to see if I can adjust it.

**Comment by AlmostPete** [comment]
Hmm. I wonder if we should use Travis then... since a majority of the players will be running Windows, having a build system that uses Windows would be preferable. Thanks for the work so far though.

**Comment by cybergeek94** [comment]
If we want to embrace cross-platform we should start early. There are CI providers that offer Windows workers but I don't think they're free.

**Comment by AlmostPete** [comment]
I know that all of the work on the original remake was done in Windows, and they had an automated build system. I think @johnku1 knows how the building was done. We should ask him. Until then, I guess a quick search for a free CI provider with Windows workers might be worthwhile.

**Comment by cybergeek94** [comment]
[Appveyor][1] is free for OSS projects. They have what we need and I've heard them recommended before. Shall I sign us up?

[1]: http://www.appveyor.com/pricing

**Comment by AlmostPete** [comment]
Sounds great! Thanks for looking.

**Comment by cybergeek94** [comment]
Activated CI with Appveyor, building e0330a8d. Deleted `travis-ci` branch.

**Comment by AlmostPete** [comment]
Could you throw a link our way once you think everything is up and running?

**Comment by cybergeek94** [comment]
I just granted admin access to `ss31/Owners` group.

Does [this link][1] lead anywhere interesting? You might need to sign in with GH.

[1]: https://ci.appveyor.com/project/cybergeek94/ss31

**Comment by AlmostPete** [comment]
It looks like the link goes to a log of the builds.

**Comment by cybergeek94** [comment]
Holy shikes, it works. Check the build logs!

**Comment by AlmostPete** [comment]
I just got the email confirming a successful build. That's very exciting, thanks for setting it up! Could you prepare a couple sentences on how we can use it and share the builds with the world?

**Comment by cybergeek94** [comment]
Well, CI is mostly about automatically checking commits and pull requests to make sure they're still building correctly. Deploying built artifacts is going to take a bit more work but I think it's possible. I can submit a PR/commit to add the badge to the readme.

**Comment by AlmostPete** [comment]
A badge would be a good way to show what the status is. That would be awesome if you could do that.
