### ISSUE TITLE
Figure out which AppVeyor webhook to delete

### ISSUE THREAD

**Issue by AlmostPete** [ss31/ss31#25]
Having 2 builds trigger every time something happens is a little annoying and redundant. Can someone look at which webhook is using @cybergeek94 's account, and delete the other one, so there is only one build.

**Comment by cybergeek94** [comment]
Mine is the higher build number. I believe @johnku1 needs to delete his project on AppVeyor or disable builds for it.

**Comment by johnku1** [comment]
I deleted my project, issue should be gone.
