### ISSUE TITLE
Get the game building on Linux / OS X

### ISSUE THREAD

**Issue by cybergeek94** [ss31/ss31#27]
I have a Xubuntu VM that I can test on, I already have it set up to build Monogame from when I was trying to get TravisCI working.

I think the current solution works, it just needs to be moved out of the Win32 folder so people don't get the wrong impression. We need to test it first, however.

- [x] Test building with the current solution in Xamarin on Linux. ([Check!][1])
- [x] Test building with the current solution via xbuild on the command line. (Didn't need any fixing!)
- [x] Remove references to Win32 from the current solution. ([Check!][2])
    - [x] Lift relevant files to the `Build/` directory.
    - [x] Update references in relevant files.
- [ ] **Optional but Recommended:** Find someone with OS X to test building there.
- [x] **Optional:** Switch back to TravisCI for testing Linux builds. ([Check!][2])

The last item is purely optional but I think we can assume that the game is building correctly on most platforms if it builds fine in both our Windows development environments and Travis' Linux workers.

I also recommend switching back to Travis CI because it's better recognized and IMO easier to use for teams. I'm not comfortable having our CI tied to my personal account with no one else able to access it.

[1]: https://github.com/ss31/ss31/pull/28
[2]: https://github.com/ss31/ss31/pull/46

**Comment by cybergeek94** [comment]
ss31 now builds and runs on Linux! Changes are in the `linux_builds` branch and will be merged shortly.

**Comment by AlmostPete** [comment]
If you think we should move back to Travis CI, I think we should go ahead and do that since you are the one managing the CI. If we want to test OSX, we could either ask @johnku1 if he knows a developer from ss14 who uses OSX, or we could wait a week, after which I will have access to a computer running OSX. The other option is to ask a member of the ss13 community, which might be hard since there aren't many people who follow us there (our sub has 8 subscribers last I checked).

**Comment by cybergeek94** [comment]
XBuild works fine on the current master, assuming `nuget restore` works (I didn't build from scratch).

**Comment by cybergeek94** [comment]
Lifted solution files and migrated back to Travis in [this PR](https://github.com/ss31/ss31/pull/46).

**Comment by cybergeek94** [comment]
Closing because mostly fulfilled. Opening an issue for OS X.
