### ISSUE TITLE
Get server and client message pumps working.

### ISSUE THREAD

**Issue by AlmostPete** [ss31/ss31#3]
Need to get the network message pumps running on both the server and the client. This will probably include implementing Network Managers on both sides, and having them poll for messages each frame.

**Comment by AlmostPete** [comment]
VERY basic message pump up and running on Client. Need to get @johnku1 to commit his changes to server before I can start work on the Server side message pump.

**Comment by johnku1** [comment]
You can continue working on this, it will be a while before I have access to my dev machine.

**Comment by AlmostPete** [comment]
Okay will do. Apologies in advance for the inevitable merge conflicts from this.
