### ISSUE TITLE
Figure out Base vs. Replaceable Code

### ISSUE THREAD

**Issue by AlmostPete** [ss31/ss31#51]
We are going to have the base code and server-specific code separated, so it is easier for custom station code to implement their own specific content and logic.

We need to figure out what code will go in the base libraries and executables, that shouldn't be modified for custom stations, and what will go in the content library, which is free to be modified and customized by custom station code.

Basically, the general categories are:

* Base Code
  * Rendering code
  * Lobby, server list, connections
  * Input handling and dispatch
  * Network handling and dispatch
  * World management and event passing
* Custom Code
  * Defining custom Items, Tiles, Entities, and Components
  * Implementing logic of game world interactions
  * Handling input events and updating accordingly
  * Handling network messages and updating accordingly

These are just very basic categories, specifics will need to be filled in before we can consider this closed.

**Comment by AlmostPete** [comment]
I will just edit this comment with what we decide as we decide it.

* Base Code
  * Base classes for Entities, Items, and Tiles, and Component.
* Custom Code

**Comment by cybergeek94** [comment]
So we should separate the true core classes from `SS31.Common` into an `SS31.Core` package, and `SS31.Common` is where the replaceable code goes. Then custom stations can have their users replace just `SS31.Common`, or we could implement some dynamic loading to `SS31.Core`.

**Comment by AlmostPete** [comment]
Closing this now as we discussed most of this in #57. Further work on code pertaining to this ticket will progress in #63.
