### ISSUE TITLE
Figure out Station code stats

### ISSUE THREAD

**Issue by AlmostPete** [ss31/ss31#57]
We need to figure out how station code will be built and distributed, and the internal structure that will allow us to load in the library and runtime and get everything up and running.

**Comment by AlmostPete** [comment]
This will need to include how we are going to get the ss31common library into a path that the ss31station code can reference, and how to build the station code into a nice folder with two files: the code library and a content .zip.

**Comment by cybergeek94** [comment]
Probably better to discuss this here. We should move all core classes (IO, bootstrapping MG and Artemis) to an `SS31.Core` package, then keep the replaceable code in `SS31.Common`. Custom stations can swap out `SS31.Common.DLL` or we can implement runtime loading in the core.

**Comment by AlmostPete** [comment]
Okay this sounds good. I can make this switch today as I'm finishing up the last couple of refactoring tasks.

**Comment by AlmostPete** [comment]
Okay I made the switch. As the code structure currently stands, there are 4 code sets in the repo. 

* SS31.Core contains all of the core classes that are shared by Client, Server, and Station and is a library. 
* SS31.Station is also a library, but that is what will implement the custom content for the server using classes provided in SS31.Core. SS31.Core will be in charge of loading the necessary classes and functions from SS31.Station at runtime. SS31.Station will be custom to each server and will be downloaded from the server when the client connects. 
* SS31.Client is an application that will provide the base setup for rendering and low level logic, such as input and network handling. It will also automatically use the information provided from SS31.Station to render the game world, items, and entities, so the modders dont have to get their hands dirty with low level stuff. All input and networking that is not handled by SS31.Client will be passed to the loaded station code.
* SS31.Server is also an application, but runs in a command line and will only be there to provide updates and messages from the server. It will also use SS31.Core to load the station code, but will only keep the station code as a reference instead of actually using it for rendering or anything. It will also keep the master list of items and is responsible for non-client updates such as atmo and the arrival and dispatch of packets from the clients.
