### ISSUE TITLE
Figure out Wiki

### ISSUE THREAD

**Issue by AlmostPete** [ss31/ss31#58]
We need to get a wiki up and running to document how the code works and how to use the project. This will be helpful for both us and other people who will customize the code in the future.

**Comment by johnku1** [comment]
Would this work?

https://github.com/ss31/ss31/wiki

**Comment by AlmostPete** [comment]
For now, I think that would work for just us, but in the future when people are trying to create their own custom station code, an actual wiki would be nice for that. Also we could combine that with a content wiki down the road as well.

**Comment by AlmostPete** [comment]
For right now, for all of the information on the codebase, which includes building, contributing, how to mod, and class info, will go into the Github wiki. Later down the road we will take a look at a real wiki for the game itself.
